services:
  - type: web
    name: funny-friend-backend
    env: python
    region: oregon  # or choose your preferred region
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: BACKEND_BASE_URL
        sync: false
